<template>
  <div class="book-directory">
    <ul class="directory">
      <BookDirectoryItem :chapterList="chapterList" />
    </ul>
  </div>
</template>

<script setup>
import BookDirectoryItem from "./BookDirecItem.vue";

const chapterList = [
  {
    F_chapter_name: "第一单元",
    F_chapter_id: 29596165,
    F_user_create: 0,
    F_period_list: null,
    F_chapter_children: [
      {
        F_chapter_name: "1 古诗二首",
        F_chapter_id: 29597165,
        F_user_create: 0,
        F_period_list: null,
        F_chapter_children: [
          {
            F_chapter_name: "村居",
            F_chapter_id: 29598165,
            F_user_create: 0,
            F_period_list: null,
            F_chapter_children: [],
          },
          {
            F_chapter_name: "咏柳",
            F_chapter_id: 29599165,
            F_user_create: 0,
            F_period_list: null,
            F_chapter_children: [],
          },
        ],
      },
      {
        F_chapter_name: "2 找春天",
        F_chapter_id: 29600165,
        F_user_create: 0,
        F_period_list: null,
        F_chapter_children: [],
      },
      {
        F_chapter_name: "3 开满鲜花的小路",
        F_chapter_id: 29601165,
        F_user_create: 0,
        F_period_list: null,
        F_chapter_children: [],
      },
      {
        F_chapter_name: "4 邓小平爷爷植树",
        F_chapter_id: 29602165,
        F_user_create: 0,
        F_period_list: null,
        F_chapter_children: [],
      },
      {
        F_chapter_name: "口语交际：注意说话的语气",
        F_chapter_id: 29603165,
        F_user_create: 0,
        F_period_list: null,
        F_chapter_children: [],
      },
      {
        F_chapter_name: "语文园地一",
        F_chapter_id: 29604165,
        F_user_create: 0,
        F_period_list: null,
        F_chapter_children: [],
      },
      {
        F_chapter_name: "快乐读书吧：读读儿童故事",
        F_chapter_id: 29605165,
        F_user_create: 0,
        F_period_list: null,
        F_chapter_children: [],
      },
    ],
  },
  {
    F_chapter_name: "第二单元",
    F_chapter_id: 29606165,
    F_user_create: 0,
    F_period_list: null,
    F_chapter_children: [
      {
        F_chapter_name: "5 雷锋叔叔，你在哪里",
        F_chapter_id: 29607165,
        F_user_create: 0,
        F_period_list: null,
        F_chapter_children: [],
      },
      {
        F_chapter_name: "6 千人糕",
        F_chapter_id: 29608165,
        F_user_create: 0,
        F_period_list: null,
        F_chapter_children: [],
      },
      {
        F_chapter_name: "7 一匹出色的马",
        F_chapter_id: 29609165,
        F_user_create: 0,
        F_period_list: null,
        F_chapter_children: [],
      },
      {
        F_chapter_name: "语文园地二",
        F_chapter_id: 29610165,
        F_user_create: 0,
        F_period_list: null,
        F_chapter_children: [],
      },
    ],
  },
  {
    F_chapter_name: "识字一",
    F_chapter_id: 29611165,
    F_user_create: 0,
    F_period_list: null,
    F_chapter_children: [
      {
        F_chapter_name: "1 神州谣",
        F_chapter_id: 29612165,
        F_user_create: 0,
        F_period_list: null,
        F_chapter_children: [],
      },
      {
        F_chapter_name: "2 传统节日",
        F_chapter_id: 29613165,
        F_user_create: 0,
        F_period_list: null,
        F_chapter_children: [],
      },
      {
        F_chapter_name: "3 “贝”的故事",
        F_chapter_id: 29614165,
        F_user_create: 0,
        F_period_list: null,
        F_chapter_children: [],
      },
      {
        F_chapter_name: "4 中国美食",
        F_chapter_id: 29615165,
        F_user_create: 0,
        F_period_list: null,
        F_chapter_children: [],
      },
      {
        F_chapter_name: "口语交际：长大以后做什么",
        F_chapter_id: 29616165,
        F_user_create: 0,
        F_period_list: null,
        F_chapter_children: [],
      },
      {
        F_chapter_name: "语文园地三",
        F_chapter_id: 29617165,
        F_user_create: 0,
        F_period_list: null,
        F_chapter_children: [],
      },
    ],
  },
  {
    F_chapter_name: "第三单元",
    F_chapter_id: 29618165,
    F_user_create: 0,
    F_period_list: null,
    F_chapter_children: [
      {
        F_chapter_name: "8 彩色的梦",
        F_chapter_id: 29619165,
        F_user_create: 0,
        F_period_list: null,
        F_chapter_children: [],
      },
      {
        F_chapter_name: "9 枫树上的喜鹊",
        F_chapter_id: 29620165,
        F_user_create: 0,
        F_period_list: null,
        F_chapter_children: [],
      },
      {
        F_chapter_name: "10 沙滩上的童话",
        F_chapter_id: 29621165,
        F_user_create: 0,
        F_period_list: null,
        F_chapter_children: [],
      },
      {
        F_chapter_name: "11 我是一只小虫子",
        F_chapter_id: 29622165,
        F_user_create: 0,
        F_period_list: null,
        F_chapter_children: [],
      },
      {
        F_chapter_name: "语文园地四",
        F_chapter_id: 29623165,
        F_user_create: 0,
        F_period_list: null,
        F_chapter_children: [],
      },
    ],
  },
  {
    F_chapter_name: "第四单元",
    F_chapter_id: 29624165,
    F_user_create: 0,
    F_period_list: null,
    F_chapter_children: [
      {
        F_chapter_name: "12 寓言二则",
        F_chapter_id: 29625165,
        F_user_create: 0,
        F_period_list: null,
        F_chapter_children: [
          {
            F_chapter_name: "亡羊补牢",
            F_chapter_id: 29626165,
            F_user_create: 0,
            F_period_list: null,
            F_chapter_children: [],
          },
          {
            F_chapter_name: "揠苗助长",
            F_chapter_id: 29627165,
            F_user_create: 0,
            F_period_list: null,
            F_chapter_children: [],
          },
        ],
      },
      {
        F_chapter_name: "13 画杨桃",
        F_chapter_id: 29628165,
        F_user_create: 0,
        F_period_list: null,
        F_chapter_children: [],
      },
      {
        F_chapter_name: "14 小马过河",
        F_chapter_id: 29629165,
        F_user_create: 0,
        F_period_list: null,
        F_chapter_children: [],
      },
      {
        F_chapter_name: "口语交际：图书借阅公约",
        F_chapter_id: 29630165,
        F_user_create: 0,
        F_period_list: null,
        F_chapter_children: [],
      },
      {
        F_chapter_name: "语文园地五",
        F_chapter_id: 29631165,
        F_user_create: 0,
        F_period_list: null,
        F_chapter_children: [],
      },
    ],
  },
  {
    F_chapter_name: "第五单元",
    F_chapter_id: 29632165,
    F_user_create: 0,
    F_period_list: null,
    F_chapter_children: [
      {
        F_chapter_name: "15 古诗二首",
        F_chapter_id: 29633165,
        F_user_create: 0,
        F_period_list: null,
        F_chapter_children: [
          {
            F_chapter_name: "晓出净慈寺送林子方",
            F_chapter_id: 29634165,
            F_user_create: 0,
            F_period_list: null,
            F_chapter_children: [],
          },
          {
            F_chapter_name: "绝句",
            F_chapter_id: 29635165,
            F_user_create: 0,
            F_period_list: null,
            F_chapter_children: [],
          },
        ],
      },
      {
        F_chapter_name: "16 雷雨",
        F_chapter_id: 29636165,
        F_user_create: 0,
        F_period_list: null,
        F_chapter_children: [],
      },
      {
        F_chapter_name: "17 要是你在野外迷了路",
        F_chapter_id: 29637165,
        F_user_create: 0,
        F_period_list: null,
        F_chapter_children: [],
      },
      {
        F_chapter_name: "18 太空生活趣事多",
        F_chapter_id: 29638165,
        F_user_create: 0,
        F_period_list: null,
        F_chapter_children: [],
      },
      {
        F_chapter_name: "语文园地六",
        F_chapter_id: 29639165,
        F_user_create: 0,
        F_period_list: null,
        F_chapter_children: [],
      },
    ],
  },
  {
    F_chapter_name: "第六单元",
    F_chapter_id: 29640165,
    F_user_create: 0,
    F_period_list: null,
    F_chapter_children: [
      {
        F_chapter_name: "19 大象的耳朵",
        F_chapter_id: 29641165,
        F_user_create: 0,
        F_period_list: null,
        F_chapter_children: [],
      },
      {
        F_chapter_name: "20 蜘蛛开店",
        F_chapter_id: 29642165,
        F_user_create: 0,
        F_period_list: null,
        F_chapter_children: [],
      },
      {
        F_chapter_name: "21 青蛙卖泥塘",
        F_chapter_id: 29643165,
        F_user_create: 0,
        F_period_list: null,
        F_chapter_children: [],
      },
      {
        F_chapter_name: "22 小毛虫",
        F_chapter_id: 29644165,
        F_user_create: 0,
        F_period_list: null,
        F_chapter_children: [],
      },
      {
        F_chapter_name: "语文园地七",
        F_chapter_id: 29645165,
        F_user_create: 0,
        F_period_list: null,
        F_chapter_children: [],
      },
    ],
  },
  {
    F_chapter_name: "第七单元",
    F_chapter_id: 29646165,
    F_user_create: 0,
    F_period_list: null,
    F_chapter_children: [
      {
        F_chapter_name: "23 祖先的摇篮",
        F_chapter_id: 29647165,
        F_user_create: 0,
        F_period_list: null,
        F_chapter_children: [],
      },
      {
        F_chapter_name: "24 当世界年纪还小的时候",
        F_chapter_id: 29648165,
        F_user_create: 0,
        F_period_list: null,
        F_chapter_children: [],
      },
      {
        F_chapter_name: "25 羿射九日",
        F_chapter_id: 29649165,
        F_user_create: 0,
        F_period_list: null,
        F_chapter_children: [],
      },
      {
        F_chapter_name: "口语交际：推荐一部动画片",
        F_chapter_id: 29650165,
        F_user_create: 0,
        F_period_list: null,
        F_chapter_children: [],
      },
      {
        F_chapter_name: "语文园地八",
        F_chapter_id: 29651165,
        F_user_create: 0,
        F_period_list: null,
        F_chapter_children: [],
      },
    ],
  },
  {
    F_chapter_name: "识字表",
    F_chapter_id: 29652165,
    F_user_create: 0,
    F_period_list: null,
    F_chapter_children: [],
  },
  {
    F_chapter_name: "写字表",
    F_chapter_id: 29653165,
    F_user_create: 0,
    F_period_list: null,
    F_chapter_children: [],
  },
  {
    F_chapter_name: "词语表",
    F_chapter_id: 29654165,
    F_user_create: 0,
    F_period_list: null,
    F_chapter_children: [],
  },
];
</script>

<style lang="less" scoped></style>
